version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:qwe123@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    links:
      - postgres