// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rpc_transfer_money.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferMoneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMoneyRequest) Reset() {
	*x = TransferMoneyRequest{}
	mi := &file_rpc_transfer_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMoneyRequest) ProtoMessage() {}

func (x *TransferMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMoneyRequest.ProtoReflect.Descriptor instead.
func (*TransferMoneyRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_money_proto_rawDescGZIP(), []int{0}
}

func (x *TransferMoneyRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *TransferMoneyRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *TransferMoneyRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferMoneyRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type TransferMoneyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfer      *Transfer              `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	FromAccount   *Account               `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     *Account               `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	FromEntry     *Entry                 `protobuf:"bytes,4,opt,name=from_entry,json=fromEntry,proto3" json:"from_entry,omitempty"`
	ToEntry       *Entry                 `protobuf:"bytes,5,opt,name=to_entry,json=toEntry,proto3" json:"to_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMoneyResponse) Reset() {
	*x = TransferMoneyResponse{}
	mi := &file_rpc_transfer_money_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMoneyResponse) ProtoMessage() {}

func (x *TransferMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_money_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMoneyResponse.ProtoReflect.Descriptor instead.
func (*TransferMoneyResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_money_proto_rawDescGZIP(), []int{1}
}

func (x *TransferMoneyResponse) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *TransferMoneyResponse) GetFromAccount() *Account {
	if x != nil {
		return x.FromAccount
	}
	return nil
}

func (x *TransferMoneyResponse) GetToAccount() *Account {
	if x != nil {
		return x.ToAccount
	}
	return nil
}

func (x *TransferMoneyResponse) GetFromEntry() *Entry {
	if x != nil {
		return x.FromEntry
	}
	return nil
}

func (x *TransferMoneyResponse) GetToEntry() *Entry {
	if x != nil {
		return x.ToEntry
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromAccountId int64                  `protobuf:"varint,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_rpc_transfer_money_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_money_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_money_proto_rawDescGZIP(), []int{2}
}

func (x *Transfer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transfer) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *Transfer) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *Transfer) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_rpc_transfer_money_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_money_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_money_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Entry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_rpc_transfer_money_proto protoreflect.FileDescriptor

const file_rpc_transfer_money_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_transfer_money.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\raccount.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x96\x01\n" +
	"\x14TransferMoneyRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xed\x01\n" +
	"\x15TransferMoneyResponse\x12(\n" +
	"\btransfer\x18\x01 \x01(\v2\f.pb.TransferR\btransfer\x12.\n" +
	"\ffrom_account\x18\x02 \x01(\v2\v.pb.AccountR\vfromAccount\x12*\n" +
	"\n" +
	"to_account\x18\x03 \x01(\v2\v.pb.AccountR\ttoAccount\x12(\n" +
	"\n" +
	"from_entry\x18\x04 \x01(\v2\t.pb.EntryR\tfromEntry\x12$\n" +
	"\bto_entry\x18\x05 \x01(\v2\t.pb.EntryR\atoEntry\"\xb9\x01\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x89\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB&Z$github.com/JaidenShall/simplebank/pbb\x06proto3"

var (
	file_rpc_transfer_money_proto_rawDescOnce sync.Once
	file_rpc_transfer_money_proto_rawDescData []byte
)

func file_rpc_transfer_money_proto_rawDescGZIP() []byte {
	file_rpc_transfer_money_proto_rawDescOnce.Do(func() {
		file_rpc_transfer_money_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_transfer_money_proto_rawDesc), len(file_rpc_transfer_money_proto_rawDesc)))
	})
	return file_rpc_transfer_money_proto_rawDescData
}

var file_rpc_transfer_money_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_transfer_money_proto_goTypes = []any{
	(*TransferMoneyRequest)(nil),  // 0: pb.TransferMoneyRequest
	(*TransferMoneyResponse)(nil), // 1: pb.TransferMoneyResponse
	(*Transfer)(nil),              // 2: pb.Transfer
	(*Entry)(nil),                 // 3: pb.Entry
	(*Account)(nil),               // 4: pb.Account
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_rpc_transfer_money_proto_depIdxs = []int32{
	2, // 0: pb.TransferMoneyResponse.transfer:type_name -> pb.Transfer
	4, // 1: pb.TransferMoneyResponse.from_account:type_name -> pb.Account
	4, // 2: pb.TransferMoneyResponse.to_account:type_name -> pb.Account
	3, // 3: pb.TransferMoneyResponse.from_entry:type_name -> pb.Entry
	3, // 4: pb.TransferMoneyResponse.to_entry:type_name -> pb.Entry
	5, // 5: pb.Transfer.created_at:type_name -> google.protobuf.Timestamp
	5, // 6: pb.Entry.created_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_transfer_money_proto_init() }
func file_rpc_transfer_money_proto_init() {
	if File_rpc_transfer_money_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_transfer_money_proto_rawDesc), len(file_rpc_transfer_money_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_transfer_money_proto_goTypes,
		DependencyIndexes: file_rpc_transfer_money_proto_depIdxs,
		MessageInfos:      file_rpc_transfer_money_proto_msgTypes,
	}.Build()
	File_rpc_transfer_money_proto = out.File
	file_rpc_transfer_money_proto_goTypes = nil
	file_rpc_transfer_money_proto_depIdxs = nil
}
