// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service_simple_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a\x16rpc_verify_email.proto\x1a\x18rpc_create_account.proto\x1a\x15rpc_get_account.proto\x1a\x17rpc_list_accounts.proto\x1a\x11rpc_deposit.proto\x1a\x12rpc_withdraw.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xdf\n" +
	"\n" +
	"\n" +
	"SimpleBank\x12\x8e\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"Q\x92A4\x12\x0fCreate new user\x1a!Use this API to create a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\xa3\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"i\x92AM\x12\n" +
	"Login user\x1a?Use this API to login user and get access token & refresh token\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\x84\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"G\x92A*\x12\vUpdate user\x1a\x1bUse this API to update user\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\x96\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"V\x92A;\x12\fVerify email\x1a+Use this API to verify user's email address\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_email\x12\x96\x01\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"P\x92A6\x12\x0eCreate account\x1a$Use this API to create a new account\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/accounts\x12\x89\x01\n" +
	"\n" +
	"GetAccount\x12\x15.pb.GetAccountRequest\x1a\x16.pb.GetAccountResponse\"L\x92A0\x12\vGet account\x1a!Use this API to get account by ID\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/accounts/{id}\x12\x88\x01\n" +
	"\fListAccounts\x12\x17.pb.ListAccountsRequest\x1a\x18.pb.ListAccountsResponse\"E\x92A.\x12\rList accounts\x1a\x1dUse this API to list accounts\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/accounts\x12\x9f\x01\n" +
	"\aDeposit\x12\x12.pb.DepositRequest\x1a\x13.pb.DepositResponse\"k\x92A<\x12\rDeposit money\x1a+Use this API to deposit money to an account\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/accounts/{account_id}/deposit\x12\xa7\x01\n" +
	"\bWithdraw\x12\x13.pb.WithdrawRequest\x1a\x14.pb.WithdrawResponse\"p\x92A@\x12\x0eWithdraw money\x1a.Use this API to withdraw money from an account\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/accounts/{account_id}/withdrawB\x8c\x01\x92Ac\x12a\n" +
	"\x0fSimple Bank API\"I\n" +
	"\fJaiden Shall\x12\x1ehttps://github.com/JaidenShall\x1a\x19shalljaiden0110@gmail.com2\x031.2Z$github.com/JaidenShall/simplebank/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),     // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),      // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),     // 2: pb.UpdateUserRequest
	(*VerifyEmailRequest)(nil),    // 3: pb.VerifyEmailRequest
	(*CreateAccountRequest)(nil),  // 4: pb.CreateAccountRequest
	(*GetAccountRequest)(nil),     // 5: pb.GetAccountRequest
	(*ListAccountsRequest)(nil),   // 6: pb.ListAccountsRequest
	(*DepositRequest)(nil),        // 7: pb.DepositRequest
	(*WithdrawRequest)(nil),       // 8: pb.WithdrawRequest
	(*CreateUserResponse)(nil),    // 9: pb.CreateUserResponse
	(*LoginUserResponse)(nil),     // 10: pb.LoginUserResponse
	(*UpdateUserResponse)(nil),    // 11: pb.UpdateUserResponse
	(*VerifyEmailResponse)(nil),   // 12: pb.VerifyEmailResponse
	(*CreateAccountResponse)(nil), // 13: pb.CreateAccountResponse
	(*GetAccountResponse)(nil),    // 14: pb.GetAccountResponse
	(*ListAccountsResponse)(nil),  // 15: pb.ListAccountsResponse
	(*DepositResponse)(nil),       // 16: pb.DepositResponse
	(*WithdrawResponse)(nil),      // 17: pb.WithdrawResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0,  // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	2,  // 2: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	3,  // 3: pb.SimpleBank.VerifyEmail:input_type -> pb.VerifyEmailRequest
	4,  // 4: pb.SimpleBank.CreateAccount:input_type -> pb.CreateAccountRequest
	5,  // 5: pb.SimpleBank.GetAccount:input_type -> pb.GetAccountRequest
	6,  // 6: pb.SimpleBank.ListAccounts:input_type -> pb.ListAccountsRequest
	7,  // 7: pb.SimpleBank.Deposit:input_type -> pb.DepositRequest
	8,  // 8: pb.SimpleBank.Withdraw:input_type -> pb.WithdrawRequest
	9,  // 9: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	10, // 10: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	11, // 11: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	12, // 12: pb.SimpleBank.VerifyEmail:output_type -> pb.VerifyEmailResponse
	13, // 13: pb.SimpleBank.CreateAccount:output_type -> pb.CreateAccountResponse
	14, // 14: pb.SimpleBank.GetAccount:output_type -> pb.GetAccountResponse
	15, // 15: pb.SimpleBank.ListAccounts:output_type -> pb.ListAccountsResponse
	16, // 16: pb.SimpleBank.Deposit:output_type -> pb.DepositResponse
	17, // 17: pb.SimpleBank.Withdraw:output_type -> pb.WithdrawResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_verify_email_proto_init()
	file_rpc_create_account_proto_init()
	file_rpc_get_account_proto_init()
	file_rpc_list_accounts_proto_init()
	file_rpc_deposit_proto_init()
	file_rpc_withdraw_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
