name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      # Updated to the latest version
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      # Updated to the latest version
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-3

    - name: Login to Amazon ECR
      id: login-ecr
      # Updated to the latest version
      uses: aws-actions/amazon-ecr-login@v2

    - name: Load secrets and save to app.env
      run:  aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

    # --- START OF CHANGES ---
    # The old "Build, tag, and push" step has been replaced with these 3 new steps.

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push multi-platform image to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/simplebank:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # --- END OF CHANGES ---
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

